---
- hosts: all
  become: true
  tags:
    - core
  remote_user: ubuntu
  gather_facts: no
  pre_tasks:
  - name: install python
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python python-pip)"
    register: output
    changed_when: output.stdout != ""

- hosts: reports
  become: true
  tags:
    - prereqs
  tasks:
    - include_role:
        name: simpl.setup

- hosts: reports
  become: true
  tags:
    - R
  tasks:
    - include_role:
        name: oefenweb.r
      vars:
        r_install_dev: true
        r_install:
          - r-recommended
        r_packages:
          - name: bookdown
          - name: dplyr
          - name: DT
          - name: htmltools
          - name: ggplot2
          - name: ggthemes
          - name: rmarkdown
          - name: scales
          - name: stringr
          - name: tinytex
          - name: viridis
          - name: purrr
          - name: tidyr
          - name: knitr
          - name: lubridate
          - name: RColorBrewer
          - name: forcats
          - name: glue
          - name: gridExtra
          - name: tidyverse

- hosts: reports
  become: yes
  tags:
    - R
  tasks:
    - name: Create rusers group
      group:
        name: rusers
        state: present
    - name: Add ubuntu user to group
      user:
        name: ubuntu
        groups: rusers
        append: yes

- hosts: reports
  become: yes
  tags:
    - R
  tasks: 
    - name: R lib permissions
      file:
        path: "{{ item }}"
        group: rusers
        mode: "2775"
        recurse: yes
        state: directory
      with_items:
        - "/usr/local/lib/R/site-library"
        - "/usr/lib/R/site-library"
        - "/usr/lib/R/library"

- hosts: reports
  tags:
    - ruby
    - apt
  gather_facts: true # https://github.com/zzet/ansible-rbenv-role/issues/37
  roles:
    - role: zzet.rbenv
      rbenv_users:
        - ubuntu
  vars:
    rbenv:
      env: user
      version: v1.1.1
      default_ruby: 2.5.1
      rubies:
      - version: 2.5.1
        env:
          RUBY_CONFIGURE_OPTS: "--disable-install-doc --enable-shared --with-jemalloc"
    rbenv_extra_depends:
      - libjemalloc1
      - libjemalloc-dev

#- hosts: reports
#  become: yes
#  tags:
#    - systemd
#    - timer
#  roles:
#    - role: data.retrieval
