---
- hosts: all
  become: true
  tags:
    - core
  remote_user: ubuntu
  gather_facts: no
  vars:
    - ansible_python_interpreter: /usr/bin/python3
  pre_tasks:
    - name: install python3
      raw: bash -c "test -e /usr/bin/python3 || (apt -qqy update && apt install -qqy python3 python-pip)"
      register: output
      changed_when: (output.stdout != "") and (output.stdout != "\r\n")
  tasks:
    - name: install apt module requirements
      shell: "dpkg-query --show -f='${Status}' python-apt || apt install -qqy aptitude python-apt"
      #args:
      #  executable: /bin/bash
      register: output
      changed_when: output.stdout != "install ok installed"

- hosts: reports
  become: true
  tags:
    - prereqs
  tasks:
    - include_role:
        name: simpl.dependencies

- hosts: reports
  become: true
  tags:
    - R
  tasks:
    - include_role:
        name: andrewrothstein.r
      vars:
        cran_apt_repo: 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/'
        r_pkgs:
          - bookdown
          - dplyr
          - DT
          - htmltools
          - ggplot2
          - ggthemes
          - rmarkdown
          - scales
          - stringr
          - tinytex
          - tools
          - utils
          - viridis
          - purrr
          - tidyr
          - knitr
          - lubridate
          - RColorBrewer
          - forcats
          - glue
          - gridExtra
          - stats
          - tidyverse

- hosts: reports
  become: yes
  tags:
    - R
  tasks:
    - name: Create rusers group
      group:
        name: rusers
        state: present
    - name: Add ubuntu user to group
      user:
        name: ubuntu
        groups: rusers
        append: yes

- hosts: reports
  become: yes
  tags:
    - R
  tasks: 
    - name: R lib permissions
      file:
        path: "{{ item }}"
        group: rusers
        mode: "2775"
        recurse: yes
        state: directory
      with_items:
        - "/usr/local/lib/R/site-library"
        - "/usr/lib/R/site-library"
        - "/usr/lib/R/library"

- hosts: reports
  tags:
    - ruby
    - apt
  gather_facts: true # https://github.com/zzet/ansible-rbenv-role/issues/37
  roles:
    - role: zzet.rbenv
      rbenv_users:
        - ubuntu
  vars:
    rbenv:
      env: user
      version: v1.1.1
      default_ruby: 2.5.1
      rubies:
      - version: 2.5.1
        env:
          RUBY_CONFIGURE_OPTS: "--disable-install-doc --enable-shared --with-jemalloc"
    rbenv_extra_depends:
      - libjemalloc1
      - libjemalloc-dev

- hosts: reports
  become: yes
  tags:
    - sql
    - r
    - ruby
  roles:
    - role: simpl.install

- hosts: reports
  become: yes
  tags:
    - sql
    - r
    - ruby
  roles:
    - role: simpl.pipeline

