---
- src: zzet.rbenv
- src: andrewrothstein.r
# cup-bearer (data retrieval timer) install from git source
- src: git+https://git.procedurallearning.org/scm/~cgross/cup-bearer.git
  name: data.retrieval
- src: oefenweb.r
