---
- name: Add ipv4 hostname to /etc/hosts
  lineinfile:
    path: /etc/hosts
    state: present
    line: "127.0.0.1 {{ansible_hostname}}"

- name: Install aptitude
  apt:
    name: aptitude
    state: present

- name: Upgrade all system packages to the latest version
  apt:
    name: "*"
    state: latest
